// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}

declare module "web-ifc/wasm" {
  /**
   * The WebAssembly module for WebIFC
   */
  export = `${string}.wasm`;
}

declare module "web-ifc/wasm-mt" {
  /**
   * The WebAssembly module for WebIFC (Multi-Threaded)
   */
  export = `${string}.wasm`;
}
